### ISSUE TITLE
[interface] handling of long file names

### ISSUE THREAD

**Issue by JPapir** [XachaB/Qumin#16]
*Hi Sacha ! I thought it could be useful to write here down some practical issues I found, just to remember they have to be fixed. This doesn't mean that I expect you to do it, I can also handle it! It's just for tracking.*

When working on NTFS file systems, even on Linux-like OS, file names are [limited](https://unix.stackexchange.com/a/619646) to 255 chars.
However, Qumin stores files with really large names. In such cases, it could raise an OSError :

`OSError: [Errno 36] File name too long: '../Results/JointPred/20240115/vlexique_short-20171031_paradigms.csv_v1.1.0-63-g6e7431d_20240115_12h03__patternsPhonsim.csv_v1.1.0-63-g6e7431d_20240115_12h14_onePredEntropies_beta0.5.csv'
`

There should be a fallback in case of such error, in order to save the computation results + a WARNING to the user.

**Comment by XachaB** [comment]
Good point, actually this was really not a good design choice. What we should do instead is use only the date and time as identifier, and export a json file with the same name which contains all the details, eg, for the above:

```json
{ "patterns": "<pattern file",

}
```

**Comment by XachaB** [comment]
This was closed by mistake, it is definitely not done yet !
