### ISSUE TITLE
[Lattices] unexpected keyword 'collections'

### ISSUE THREAD

**Issue by JPapir** [XachaB/Qumin#18]
Got following error on branch RemoveAliases, just by running `qumin.lattice` on very basic test patterns.
Looks like collections (in kwargs) are passed to `table_to_context`, but I don't know this error is normal behaviour, or if collections should theoretically be an argument for `table_to_context`. Note also the very weird package imports at the top of the file `qumin/lattice/lattice.py` 

I am not familiar with this part of the code, so I just put it there :

```
Traceback (most recent call last):
  File "PATH/Qumin/bin/qumin.lattice", line 33, in <module>
    sys.exit(load_entry_point('qumin', 'console_scripts', 'qumin.lattice')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH/Qumin/qumin/make_lattice.py", line 164, in lattice_command
    main(args)
  File "PATH/Qumin/qumin/make_lattice.py", line 70, in main
    lattice = ICLattice(pat_table.loc[list(microclasses), :], microclasses,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH/Qumin/qumin/lattice/lattice.py", line 156, in __init__
    self.context = table_to_context(dataframe, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: table_to_context() got an unexpected keyword argument 'collections'
```

**Comment by XachaB** [comment]
That's an easy fix, a keyword argument I forgot to rename everywhere !
