### ISSUE TITLE
[PyPi] missing js / css files for lattice script

### ISSUE THREAD

**Issue by JPapir** [XachaB/Qumin#26]
(to fix for #22)

When installing with PyPi, the following files are missing from the package:

- [HighlightSubTrees.js](https://github.com/XachaB/Qumin/blob/dev/src/qumin/lattice/HighlightSubTrees.js)
- [table.css](https://github.com/XachaB/Qumin/blob/dev/src/qumin/lattice/table.css)

If no mpld3 is not installed, this is fine. But if mpld3 is available, it raises the following error when  `qumin.lattice --html` :

```  File "/venv/lib/python3.9/site-packages/qumin/lattice/lattice.py", line 461, in _HighlightSubTrees
    JAVASCRIPT = _load_external_text("HighlightSubTrees.js")
  File "/venv/lib/python3.9/site-packages/qumin/lattice/lattice.py", line 34, in _load_external_text
    open(join(dirname(__file__), filename), "r", encoding="utf-8").readlines())
FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages/qumin/lattice/HighlightSubTrees.js'
```

**Comment by XachaB** [comment]
Solved by commit c7bb86a9d7285d2e5eb65d7b0e9366a63a464575
