### ISSUE TITLE
[Regex] Broken regex produced with ? quantifier

### ISSUE THREAD

**Issue by JPapir** [XachaB/Qumin#38]
I tried to reimplement a more detailed view of entropy in the log. (eg : entropy for each class, etc, as in Qumin v1.0's quality check). While doing this, I discovered an unexpected behaviour :

I run on the standard branch, with overabundant=False everywhere.
I use **an overabundant dataset** (Livonian).
I run a computation between two overabundant cells.

In the log, I get the following entry:

```
## Class n°0 (5433 members).

|    | Pattern                           | Example                                                                   |   Size |   P(Pattern|class) |
|---:|:----------------------------------|:--------------------------------------------------------------------------|-------:|-------------------:|
|  0 | st ⇌ ʒ / X+[-str -low -pre -tri]_ | ȭŗdõbkušt_18029: ɯː rʲ d ɯ b k u ʃˑ t iː s t  → ɯː rʲ d ɯ b k u ʃˑ t iː ʒ |   4122 |           0.758697 |
```

The probability of the pattern should be 1, not 0.7... The underlying class is as follows:

```
lexeme
Jōņȭdõg_13715                        st ⇌ ʒ / X+[-str -low -pre -tri]_
abbõndajāji_11570    [-voic]t ⇌ [+C_h +voic -C_l] / X+[-lat][-round...
abbõnz_11571                         st ⇌ ʒ / X+[-str -low -pre -tri]_
abesīv_11573                         st ⇌ ʒ / X+[-str -low -pre -tri]_
abjelāmi_11575       [-voic]t ⇌ [+C_h +voic -C_l] / X+[-lat][-round...
```

Origin of the issue: The source of grouping is inconsistent with the grouped items (displaying two patterns). This possibly comes from the overabundant dataset.

 I will investigate further later, but this is a big issue. I am wondering if it only affects the log, or also the fast computation?

**Comment by XachaB** [comment]
I'll have a look and a try at it, I don't think your solution looks right, but having the problem clearly outlined like this is very useful !

**Comment by XachaB** [comment]
Your solution _was_ right, just in the wrong place. I've added a test and tidied up
